[workspace]
resolver = "2"
members = [
	"constants",
	"core",
	"substrate",
]

[workspace.package]
version = "1.0.1"
authors = ["Quantus Network Developers <hello@quantus.com>"]
homepage = "https://quantus.com"
repository = "https://github.com/Quantus-Network/qp-poseidon"
license = "MIT-0"
edition = "2021"

[workspace.dependencies]
codec = { version = "3.7.5", default-features = false, package = "parity-scale-codec" }
criterion = { version = "0.5", features = ["html_reports"] }
ctor = "0.5.0"
env_logger = "0.11.8"
hex = "0.4.3"
log = { version = "0.4.22", default-features = false }
p3-field = { version = "0.3.0", default-features = false }
p3-goldilocks = { version = "0.3.0", default-features = false }
p3-poseidon2 = { version = "0.3.0", default-features = false }
p3-symmetric = { version = "0.3.0", default-features = false }
qp-plonky2 = { version = "1.1.2", default-features = false, features = [
	"no_random",
] }
qp-poseidon-constants = { path = "./constants", default-features = false }
qp-poseidon-core = { path = "./core", default-features = false }
rand = { version = "0.9", default-features = false, features = ["small_rng"] }
rand_chacha = { version = "0.9", default-features = false }
scale-info = { version = "2.11.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.217", default-features = false }
sp-core = { version = "37.0.0", default-features = false }
sp-runtime = { version = "42.0.0", default-features = false }
sp-storage = { version = "22.0.0", default-features = false }
sp-trie = { version = "40.0.0", default-features = false }
